### ISSUE TITLE
X265?

### ISSUE THREAD

**Issue by PiDockMedia** [jaymoulin/docker-rpi-plex-video-converter#7]
Have you thought about a version of this that encodes to the smaller x265 codec? I love the recursive fire and forget aspect of this docker. I would just ;love the smaller x265 codes size.

**Comment by jaymoulin** [comment]
Won't do. Raspberry can't handle transcoding from h265

**Comment by PiDockMedia** [comment]
The Raspberry Pi 4 can do h265/4K! The 3 can do x265/1080p but only if overclocked. Any chance you’ll reconsider? I’d love to stream direct x265 encoded content to my Pi without transcoding, and I love the simplicity of your docker.

**Comment by jaymoulin** [comment]
I don't own a Rpi4 so I'm not able to test this. But I tested on an overclocked rpi3 and plex is trancoding h265 resulting in a 800% cpu overload then freeze. This said, I don't think I will reconsider since the purpose of this image is to make things work. 
You can fork this image and replace h264 to h265 if you really need to do it but be sure everything keep running as expected.

**Comment by PiDockMedia** [comment]
Wow! My board is ordered but has not arrived. I'll give it a try once it does and report back.
